
package ru.sentinelcredit.bi;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ReportService", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReportService {


    /**
     * 
     * @param userID
     * @param templateFileName
     * @param folderAbsolutePathURL
     * @param templateData
     * @param xliffData
     * @param xliffFileName
     * @param updateFlag
     * @param password
     * @param reportName
     * @param dataModelURL
     * @return
     *     returns java.lang.String
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "createReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "createReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.CreateReport")
    @ResponseWrapper(localName = "createReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.CreateReportResponse")
    public String createReport(
        @WebParam(name = "reportName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportName,
        @WebParam(name = "folderAbsolutePathURL", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String folderAbsolutePathURL,
        @WebParam(name = "dataModelURL", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String dataModelURL,
        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateFileName,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] templateData,
        @WebParam(name = "XLIFFFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String xliffFileName,
        @WebParam(name = "XLIFFData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] xliffData,
        @WebParam(name = "updateFlag", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        boolean updateFlag,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param reportRequest
     * @param password
     * @return
     *     returns scm.bi.ParamNameValues
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getReportParametersReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getReportParameters", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetReportParameters")
    @ResponseWrapper(localName = "getReportParametersResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetReportParametersResponse")
    public ParamNameValues getReportParameters(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        ReportRequest reportRequest,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param templateID
     * @param locale
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns byte[]
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getTemplateReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getTemplate", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetTemplate")
    @ResponseWrapper(localName = "getTemplateResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetTemplateResponse")
    public byte[] getTemplate(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateID,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param reportRequest
     * @param password
     * @return
     *     returns scm.bi.ReportResponse
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "runReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "runReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.RunReport")
    @ResponseWrapper(localName = "runReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.RunReportResponse")
    public ReportResponse runReport(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        ReportRequest reportRequest,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportRequest
     * @param bipSessionToken
     * @return
     *     returns scm.bi.ReportResponse
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "runReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "runReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.RunReportInSession")
    @ResponseWrapper(localName = "runReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.RunReportInSessionResponse")
    public ReportResponse runReportInSession(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        ReportRequest reportRequest,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param reportRequest
     * @param password
     * @return
     *     returns scm.bi.ReportResponse
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "runDataModelReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "runDataModel", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.RunDataModel")
    @ResponseWrapper(localName = "runDataModelResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.RunDataModelResponse")
    public ReportResponse runDataModel(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        ReportRequest reportRequest,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportRequest
     * @param bipSessionToken
     * @return
     *     returns scm.bi.ReportResponse
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "runDataModelInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "runDataModelInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.RunDataModelInSession")
    @ResponseWrapper(localName = "runDataModelInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.RunDataModelInSessionResponse")
    public ReportResponse runDataModelInSession(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        ReportRequest reportRequest,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns scm.bi.ReportDefinition
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getReportDefinitionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getReportDefinition", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetReportDefinition")
    @ResponseWrapper(localName = "getReportDefinitionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetReportDefinitionResponse")
    public ReportDefinition getReportDefinition(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param reportAbsolutePath
     * @return
     *     returns scm.bi.ReportDefinition
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getReportDefinitionInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getReportDefinitionInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetReportDefinitionInSession")
    @ResponseWrapper(localName = "getReportDefinitionInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetReportDefinitionInSessionResponse")
    public ReportDefinition getReportDefinitionInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns byte[]
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getReportSampleDataReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getReportSampleData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetReportSampleData")
    @ResponseWrapper(localName = "getReportSampleDataResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetReportSampleDataResponse")
    public byte[] getReportSampleData(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param reportAbsolutePath
     * @return
     *     returns byte[]
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getReportSampleDataInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getReportSampleDataInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetReportSampleDataInSession")
    @ResponseWrapper(localName = "getReportSampleDataInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetReportSampleDataInSessionResponse")
    public byte[] getReportSampleDataInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param locale
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns byte[]
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getXDOSchemaReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getXDOSchema", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetXDOSchema")
    @ResponseWrapper(localName = "getXDOSchemaResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetXDOSchemaResponse")
    public byte[] getXDOSchema(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param locale
     * @param reportAbsolutePath
     * @return
     *     returns byte[]
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getXDOSchemaInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getXDOSchemaInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetXDOSchemaInSession")
    @ResponseWrapper(localName = "getXDOSchemaInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetXDOSchemaInSessionResponse")
    public byte[] getXDOSchemaInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param templateID
     * @param bipSessionToken
     * @param locale
     * @param reportAbsolutePath
     * @return
     *     returns byte[]
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getTemplateInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getTemplateInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetTemplateInSession")
    @ResponseWrapper(localName = "getTemplateInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetTemplateInSessionResponse")
    public byte[] getTemplateInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateID,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportRequest
     * @param bipSessionToken
     * @return
     *     returns scm.bi.ParamNameValues
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getReportParametersInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getReportParametersInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetReportParametersInSession")
    @ResponseWrapper(localName = "getReportParametersInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetReportParametersInSessionResponse")
    public ParamNameValues getReportParametersInSession(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        ReportRequest reportRequest,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param templateID
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns java.util.List<scm.bi.ParamNameValue>
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getTemplateParametersReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getTemplateParameters", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetTemplateParameters")
    @ResponseWrapper(localName = "getTemplateParametersResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetTemplateParametersResponse")
    public List<ParamNameValue> getTemplateParameters(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param templateID
     * @param bipSessionToken
     * @param reportAbsolutePath
     * @return
     *     returns java.util.List<scm.bi.ParamNameValue>
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getTemplateParametersInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getTemplateParametersInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetTemplateParametersInSession")
    @ResponseWrapper(localName = "getTemplateParametersInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.GetTemplateParametersInSessionResponse")
    public List<ParamNameValue> getTemplateParametersInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param templateFileName
     * @param folderAbsolutePathURL
     * @param templateData
     * @param xliffData
     * @param xliffFileName
     * @param bipSessionToken
     * @param updateFlag
     * @param reportName
     * @param dataModelURL
     * @return
     *     returns java.lang.String
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "createReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "createReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.CreateReportInSession")
    @ResponseWrapper(localName = "createReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.CreateReportInSessionResponse")
    public String createReportInSession(
        @WebParam(name = "reportName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportName,
        @WebParam(name = "folderAbsolutePathURL", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String folderAbsolutePathURL,
        @WebParam(name = "dataModelURL", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String dataModelURL,
        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateFileName,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] templateData,
        @WebParam(name = "XLIFFFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String xliffFileName,
        @WebParam(name = "XLIFFData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] xliffData,
        @WebParam(name = "updateFlag", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        boolean updateFlag,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param newReportDefn
     * @param password
     * @param reportAbsPath
     * @return
     *     returns boolean
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "updateReportDefinitionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "updateReportDefinition", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UpdateReportDefinition")
    @ResponseWrapper(localName = "updateReportDefinitionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UpdateReportDefinitionResponse")
    public boolean updateReportDefinition(
        @WebParam(name = "reportAbsPath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsPath,
        @WebParam(name = "newReportDefn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        ReportDefinition newReportDefn,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param newReportDefn
     * @param reportAbsPath
     * @return
     *     returns boolean
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "updateReportDefinitionInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "updateReportDefinitionInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UpdateReportDefinitionInSession")
    @ResponseWrapper(localName = "updateReportDefinitionInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UpdateReportDefinitionInSessionResponse")
    public boolean updateReportDefinitionInSession(
        @WebParam(name = "reportAbsPath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsPath,
        @WebParam(name = "newReportDefn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        ReportDefinition newReportDefn,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param templateType
     * @param templateData
     * @param locale
     * @param password
     * @param reportAbsolutePath
     * @param templateName
     * @return
     *     returns boolean
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadTemplateForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "uploadTemplateForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UploadTemplateForReport")
    @ResponseWrapper(localName = "uploadTemplateForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UploadTemplateForReportResponse")
    public boolean uploadTemplateForReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateName,
        @WebParam(name = "templateType", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateType,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] templateData,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param templateType
     * @param templateData
     * @param bipSessionToken
     * @param locale
     * @param reportAbsolutePath
     * @param templateName
     * @return
     *     returns boolean
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadTemplateForReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "uploadTemplateForReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UploadTemplateForReportInSession")
    @ResponseWrapper(localName = "uploadTemplateForReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UploadTemplateForReportInSessionResponse")
    public boolean uploadTemplateForReportInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateName,
        @WebParam(name = "templateType", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateType,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] templateData,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param templateData
     * @param locale
     * @param password
     * @param reportAbsolutePath
     * @param templateName
     * @return
     *     returns boolean
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "updateTemplateForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "updateTemplateForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UpdateTemplateForReport")
    @ResponseWrapper(localName = "updateTemplateForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UpdateTemplateForReportResponse")
    public boolean updateTemplateForReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateName,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] templateData,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param templateData
     * @param bipSessionToken
     * @param locale
     * @param reportAbsolutePath
     * @param templateName
     * @return
     *     returns boolean
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "updateTemplateForReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "updateTemplateForReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UpdateTemplateForReportInSession")
    @ResponseWrapper(localName = "updateTemplateForReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UpdateTemplateForReportInSessionResponse")
    public boolean updateTemplateForReportInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateName,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] templateData,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param templateFileName
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "removeTemplateForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "removeTemplateForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.RemoveTemplateForReport")
    @ResponseWrapper(localName = "removeTemplateForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.RemoveTemplateForReportResponse")
    public boolean removeTemplateForReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateFileName,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param templateFileName
     * @param bipSessionToken
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "removeTemplateForReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "removeTemplateForReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.RemoveTemplateForReportInSession")
    @ResponseWrapper(localName = "removeTemplateForReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.RemoveTemplateForReportInSessionResponse")
    public boolean removeTemplateForReportInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateFileName,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param xliffData
     * @param locale
     * @param layoutFileName
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadXLIFFForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "uploadXLIFFForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UploadXLIFFForReport")
    @ResponseWrapper(localName = "uploadXLIFFForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UploadXLIFFForReportResponse")
    public boolean uploadXLIFFForReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "xliffData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] xliffData,
        @WebParam(name = "layoutFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String layoutFileName,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param xliffData
     * @param bipSessionToken
     * @param locale
     * @param layoutFileName
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "updateXLIFFForReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "updateXLIFFForReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UpdateXLIFFForReportInSession")
    @ResponseWrapper(localName = "updateXLIFFForReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UpdateXLIFFForReportInSessionResponse")
    public boolean updateXLIFFForReportInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "xliffData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] xliffData,
        @WebParam(name = "layoutFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String layoutFileName,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param xliffData
     * @param locale
     * @param layoutFileName
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "updateXLIFFForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "updateXLIFFForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UpdateXLIFFForReport")
    @ResponseWrapper(localName = "updateXLIFFForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UpdateXLIFFForReportResponse")
    public boolean updateXLIFFForReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "xliffData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] xliffData,
        @WebParam(name = "layoutFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String layoutFileName,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param xliffData
     * @param bipSessionToken
     * @param locale
     * @param layoutFileName
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws InvalidParametersException_Exception
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadXLIFFForReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "uploadXLIFFForReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UploadXLIFFForReportInSession")
    @ResponseWrapper(localName = "uploadXLIFFForReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UploadXLIFFForReportInSessionResponse")
    public boolean uploadXLIFFForReportInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "xliffData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] xliffData,
        @WebParam(name = "layoutFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String layoutFileName,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportRawDataChunk
     * @param userID
     * @param fileID
     * @param reportDataChunk
     * @param password
     * @return
     *     returns java.lang.String
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadReportDataChunkReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "uploadReportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UploadReportDataChunk")
    @ResponseWrapper(localName = "uploadReportDataChunkResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UploadReportDataChunkResponse")
    public String uploadReportDataChunk(
        @WebParam(name = "fileID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String fileID,
        @WebParam(name = "reportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] reportDataChunk,
        @WebParam(name = "reportRawDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportRawDataChunk,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportRawDataChunk
     * @param fileID
     * @param bipSessionToken
     * @param reportDataChunk
     * @return
     *     returns java.lang.String
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadReportDataChunkInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "uploadReportDataChunkInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UploadReportDataChunkInSession")
    @ResponseWrapper(localName = "uploadReportDataChunkInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.UploadReportDataChunkInSessionResponse")
    public String uploadReportDataChunkInSession(
        @WebParam(name = "fileID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String fileID,
        @WebParam(name = "reportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] reportDataChunk,
        @WebParam(name = "reportRawDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportRawDataChunk,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param fileID
     * @param beginIdx
     * @param password
     * @param size
     * @return
     *     returns scm.bi.ReportDataChunk
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "downloadReportDataChunkReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "downloadReportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.DownloadReportDataChunk")
    @ResponseWrapper(localName = "downloadReportDataChunkResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.DownloadReportDataChunkResponse")
    public ReportDataChunk downloadReportDataChunk(
        @WebParam(name = "fileID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String fileID,
        @WebParam(name = "beginIdx", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        int beginIdx,
        @WebParam(name = "size", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        int size,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param fileID
     * @param beginIdx
     * @param bipSessionToken
     * @param size
     * @return
     *     returns scm.bi.ReportDataChunk
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "downloadReportDataChunkInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "downloadReportDataChunkInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.DownloadReportDataChunkInSession")
    @ResponseWrapper(localName = "downloadReportDataChunkInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi.DownloadReportDataChunkInSessionResponse")
    public ReportDataChunk downloadReportDataChunkInSession(
        @WebParam(name = "fileID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String fileID,
        @WebParam(name = "beginIdx", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        int beginIdx,
        @WebParam(name = "size", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        int size,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, OperationFailedException_Exception
    ;

}
