
package ru.sentinelcredit.bi12;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ReportService", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReportService {


    /**
     * 
     * @param userID
     * @param templateID
     * @param locale
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns byte[]
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getTemplateReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getTemplate", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetTemplate")
    @ResponseWrapper(localName = "getTemplateResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetTemplateResponse")
    public byte[] getTemplate(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateID,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param templateFileName
     * @param folderAbsolutePathURL
     * @param templateData
     * @param xliffData
     * @param xliffFileName
     * @param updateFlag
     * @param password
     * @param reportName
     * @param dataModelURL
     * @return
     *     returns java.lang.String
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "createReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "createReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.CreateReport")
    @ResponseWrapper(localName = "createReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.CreateReportResponse")
    public String createReport(
        @WebParam(name = "reportName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportName,
        @WebParam(name = "folderAbsolutePathURL", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String folderAbsolutePathURL,
        @WebParam(name = "dataModelURL", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String dataModelURL,
        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateFileName,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] templateData,
        @WebParam(name = "XLIFFFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String xliffFileName,
        @WebParam(name = "XLIFFData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] xliffData,
        @WebParam(name = "updateFlag", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        boolean updateFlag,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param reportAbsolutePath
     * @return
     *     returns scm.bi12.ReportDefinition
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getReportDefinitionInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getReportDefinitionInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetReportDefinitionInSession")
    @ResponseWrapper(localName = "getReportDefinitionInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetReportDefinitionInSessionResponse")
    public ReportDefinition getReportDefinitionInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param newReportDefn
     * @param reportAbsPath
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "updateReportDefinitionInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "updateReportDefinitionInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UpdateReportDefinitionInSession")
    @ResponseWrapper(localName = "updateReportDefinitionInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UpdateReportDefinitionInSessionResponse")
    public boolean updateReportDefinitionInSession(
        @WebParam(name = "reportAbsPath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsPath,
        @WebParam(name = "newReportDefn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        ReportDefinition newReportDefn,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param objectPath
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "removeObjectFromCacheInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "removeObjectFromCacheInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.RemoveObjectFromCacheInSession")
    @ResponseWrapper(localName = "removeObjectFromCacheInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.RemoveObjectFromCacheInSessionResponse")
    public boolean removeObjectFromCacheInSession(
        @WebParam(name = "objectPath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String objectPath,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param templateData
     * @param bipSessionToken
     * @param locale
     * @param reportAbsolutePath
     * @param templateName
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "updateTemplateForReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "updateTemplateForReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UpdateTemplateForReportInSession")
    @ResponseWrapper(localName = "updateTemplateForReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UpdateTemplateForReportInSessionResponse")
    public boolean updateTemplateForReportInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateName,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] templateData,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param reportRequest
     * @param password
     * @return
     *     returns scm.bi12.ParamNameValues
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getReportParametersReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getReportParameters", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetReportParameters")
    @ResponseWrapper(localName = "getReportParametersResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetReportParametersResponse")
    public ParamNameValues getReportParameters(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        ReportRequest reportRequest,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param reportRequest
     * @param password
     * @return
     *     returns scm.bi12.ReportResponse
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "runReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "runReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.RunReport")
    @ResponseWrapper(localName = "runReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.RunReportResponse")
    public ReportResponse runReport(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        ReportRequest reportRequest,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param templateID
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getTemplateAvailableLocalesReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getTemplateAvailableLocales", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetTemplateAvailableLocales")
    @ResponseWrapper(localName = "getTemplateAvailableLocalesResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetTemplateAvailableLocalesResponse")
    public List<String> getTemplateAvailableLocales(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportRequest
     * @param bipSessionToken
     * @return
     *     returns scm.bi12.ReportResponse
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "runReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "runReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.RunReportInSession")
    @ResponseWrapper(localName = "runReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.RunReportInSessionResponse")
    public ReportResponse runReportInSession(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        ReportRequest reportRequest,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param reportRequest
     * @param password
     * @return
     *     returns scm.bi12.ReportResponse
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "runDataModelReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "runDataModel", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.RunDataModel")
    @ResponseWrapper(localName = "runDataModelResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.RunDataModelResponse")
    public ReportResponse runDataModel(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        ReportRequest reportRequest,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportRequest
     * @param bipSessionToken
     * @return
     *     returns scm.bi12.ReportResponse
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "runDataModelInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "runDataModelInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.RunDataModelInSession")
    @ResponseWrapper(localName = "runDataModelInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.RunDataModelInSessionResponse")
    public ReportResponse runDataModelInSession(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        ReportRequest reportRequest,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns scm.bi12.ReportDefinition
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getReportDefinitionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getReportDefinition", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetReportDefinition")
    @ResponseWrapper(localName = "getReportDefinitionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetReportDefinitionResponse")
    public ReportDefinition getReportDefinition(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns scm.bi12.MobileAppDefinition
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getMobileAppDefinitionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getMobileAppDefinition", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetMobileAppDefinition")
    @ResponseWrapper(localName = "getMobileAppDefinitionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetMobileAppDefinitionResponse")
    public MobileAppDefinition getMobileAppDefinition(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param reportAbsolutePath
     * @return
     *     returns scm.bi12.MobileAppDefinition
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getMobileAppDefinitionInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getMobileAppDefinitionInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetMobileAppDefinitionInSession")
    @ResponseWrapper(localName = "getMobileAppDefinitionInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetMobileAppDefinitionInSessionResponse")
    public MobileAppDefinition getMobileAppDefinitionInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns byte[]
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getReportSampleDataReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getReportSampleData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetReportSampleData")
    @ResponseWrapper(localName = "getReportSampleDataResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetReportSampleDataResponse")
    public byte[] getReportSampleData(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param reportAbsolutePath
     * @return
     *     returns byte[]
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getReportSampleDataInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getReportSampleDataInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetReportSampleDataInSession")
    @ResponseWrapper(localName = "getReportSampleDataInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetReportSampleDataInSessionResponse")
    public byte[] getReportSampleDataInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param locale
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns byte[]
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getXDOSchemaReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getXDOSchema", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetXDOSchema")
    @ResponseWrapper(localName = "getXDOSchemaResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetXDOSchemaResponse")
    public byte[] getXDOSchema(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param locale
     * @param reportAbsolutePath
     * @return
     *     returns byte[]
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getXDOSchemaInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getXDOSchemaInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetXDOSchemaInSession")
    @ResponseWrapper(localName = "getXDOSchemaInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetXDOSchemaInSessionResponse")
    public byte[] getXDOSchemaInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param templateID
     * @param bipSessionToken
     * @param reportAbsolutePath
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getTemplateAvailableLocalesInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getTemplateAvailableLocalesInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetTemplateAvailableLocalesInSession")
    @ResponseWrapper(localName = "getTemplateAvailableLocalesInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetTemplateAvailableLocalesInSessionResponse")
    public List<String> getTemplateAvailableLocalesInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param templateID
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getTemplateAvailableXLIFFsReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getTemplateAvailableXLIFFs", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetTemplateAvailableXLIFFs")
    @ResponseWrapper(localName = "getTemplateAvailableXLIFFsResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetTemplateAvailableXLIFFsResponse")
    public List<String> getTemplateAvailableXLIFFs(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param templateID
     * @param bipSessionToken
     * @param reportAbsolutePath
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getTemplateAvailableXLIFFsInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getTemplateAvailableXLIFFsInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetTemplateAvailableXLIFFsInSession")
    @ResponseWrapper(localName = "getTemplateAvailableXLIFFsInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetTemplateAvailableXLIFFsInSessionResponse")
    public List<String> getTemplateAvailableXLIFFsInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param templateID
     * @param bipSessionToken
     * @param locale
     * @param reportAbsolutePath
     * @return
     *     returns byte[]
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getTemplateInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getTemplateInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetTemplateInSession")
    @ResponseWrapper(localName = "getTemplateInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetTemplateInSessionResponse")
    public byte[] getTemplateInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateID,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportRequest
     * @param bipSessionToken
     * @return
     *     returns scm.bi12.ParamNameValues
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getReportParametersInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getReportParametersInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetReportParametersInSession")
    @ResponseWrapper(localName = "getReportParametersInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetReportParametersInSessionResponse")
    public ParamNameValues getReportParametersInSession(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        ReportRequest reportRequest,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param templateID
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns java.util.List<scm.bi12.ParamNameValue>
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getTemplateParametersReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getTemplateParameters", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetTemplateParameters")
    @ResponseWrapper(localName = "getTemplateParametersResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetTemplateParametersResponse")
    public List<ParamNameValue> getTemplateParameters(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateID,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param templateID
     * @param bipSessionToken
     * @param reportAbsolutePath
     * @return
     *     returns java.util.List<scm.bi12.ParamNameValue>
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getTemplateParametersInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getTemplateParametersInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetTemplateParametersInSession")
    @ResponseWrapper(localName = "getTemplateParametersInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetTemplateParametersInSessionResponse")
    public List<ParamNameValue> getTemplateParametersInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateID,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param connectionName
     * @param password
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getListOfSubjectAreaReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getListOfSubjectArea", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetListOfSubjectArea")
    @ResponseWrapper(localName = "getListOfSubjectAreaResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetListOfSubjectAreaResponse")
    public List<String> getListOfSubjectArea(
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password,
        @WebParam(name = "connectionName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String connectionName)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param connectionName
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "getListOfSubjectAreaInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "getListOfSubjectAreaInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetListOfSubjectAreaInSession")
    @ResponseWrapper(localName = "getListOfSubjectAreaInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.GetListOfSubjectAreaInSessionResponse")
    public List<String> getListOfSubjectAreaInSession(
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken,
        @WebParam(name = "connectionName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String connectionName)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param templateFileName
     * @param folderAbsolutePathURL
     * @param templateData
     * @param xliffData
     * @param xliffFileName
     * @param bipSessionToken
     * @param updateFlag
     * @param reportName
     * @param dataModelURL
     * @return
     *     returns java.lang.String
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "createReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "createReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.CreateReportInSession")
    @ResponseWrapper(localName = "createReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.CreateReportInSessionResponse")
    public String createReportInSession(
        @WebParam(name = "reportName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportName,
        @WebParam(name = "folderAbsolutePathURL", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String folderAbsolutePathURL,
        @WebParam(name = "dataModelURL", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String dataModelURL,
        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateFileName,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] templateData,
        @WebParam(name = "XLIFFFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String xliffFileName,
        @WebParam(name = "XLIFFData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] xliffData,
        @WebParam(name = "updateFlag", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        boolean updateFlag,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param newReportDefn
     * @param password
     * @param reportAbsPath
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "updateReportDefinitionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "updateReportDefinition", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UpdateReportDefinition")
    @ResponseWrapper(localName = "updateReportDefinitionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UpdateReportDefinitionResponse")
    public boolean updateReportDefinition(
        @WebParam(name = "reportAbsPath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsPath,
        @WebParam(name = "newReportDefn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        ReportDefinition newReportDefn,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param objectPath
     * @param password
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "removeObjectFromCacheReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "removeObjectFromCache", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.RemoveObjectFromCache")
    @ResponseWrapper(localName = "removeObjectFromCacheResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.RemoveObjectFromCacheResponse")
    public boolean removeObjectFromCache(
        @WebParam(name = "objectPath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String objectPath,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param password
     * @param newMobileAppDefn
     * @param reportAbsPath
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "updateMobileAppDefinitionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "updateMobileAppDefinition", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UpdateMobileAppDefinition")
    @ResponseWrapper(localName = "updateMobileAppDefinitionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UpdateMobileAppDefinitionResponse")
    public boolean updateMobileAppDefinition(
        @WebParam(name = "reportAbsPath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsPath,
        @WebParam(name = "newMobileAppDefn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        MobileAppDefinition newMobileAppDefn,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param bipSessionToken
     * @param newMobileAppDefn
     * @param reportAbsPath
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "updateMobileAppDefinitionInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "updateMobileAppDefinitionInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UpdateMobileAppDefinitionInSession")
    @ResponseWrapper(localName = "updateMobileAppDefinitionInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UpdateMobileAppDefinitionInSessionResponse")
    public boolean updateMobileAppDefinitionInSession(
        @WebParam(name = "reportAbsPath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsPath,
        @WebParam(name = "newMobileAppDefn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        MobileAppDefinition newMobileAppDefn,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param templateType
     * @param templateData
     * @param locale
     * @param password
     * @param reportAbsolutePath
     * @param templateName
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadTemplateForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "uploadTemplateForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UploadTemplateForReport")
    @ResponseWrapper(localName = "uploadTemplateForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UploadTemplateForReportResponse")
    public boolean uploadTemplateForReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateName,
        @WebParam(name = "templateType", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateType,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] templateData,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param templateType
     * @param templateData
     * @param bipSessionToken
     * @param locale
     * @param reportAbsolutePath
     * @param templateName
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadTemplateForReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "uploadTemplateForReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UploadTemplateForReportInSession")
    @ResponseWrapper(localName = "uploadTemplateForReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UploadTemplateForReportInSessionResponse")
    public boolean uploadTemplateForReportInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateName,
        @WebParam(name = "templateType", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateType,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] templateData,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param templateData
     * @param locale
     * @param password
     * @param reportAbsolutePath
     * @param templateName
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "updateTemplateForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "updateTemplateForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UpdateTemplateForReport")
    @ResponseWrapper(localName = "updateTemplateForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UpdateTemplateForReportResponse")
    public boolean updateTemplateForReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateName,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] templateData,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param templateFileName
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "removeTemplateForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "removeTemplateForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.RemoveTemplateForReport")
    @ResponseWrapper(localName = "removeTemplateForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.RemoveTemplateForReportResponse")
    public boolean removeTemplateForReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateFileName,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param templateFileName
     * @param bipSessionToken
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "removeTemplateForReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "removeTemplateForReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.RemoveTemplateForReportInSession")
    @ResponseWrapper(localName = "removeTemplateForReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.RemoveTemplateForReportInSessionResponse")
    public boolean removeTemplateForReportInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String templateFileName,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param xliffData
     * @param locale
     * @param layoutFileName
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadXLIFFForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "uploadXLIFFForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UploadXLIFFForReport")
    @ResponseWrapper(localName = "uploadXLIFFForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UploadXLIFFForReportResponse")
    public boolean uploadXLIFFForReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "xliffData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] xliffData,
        @WebParam(name = "layoutFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String layoutFileName,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param xliffData
     * @param bipSessionToken
     * @param locale
     * @param layoutFileName
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "updateXLIFFForReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "updateXLIFFForReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UpdateXLIFFForReportInSession")
    @ResponseWrapper(localName = "updateXLIFFForReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UpdateXLIFFForReportInSessionResponse")
    public boolean updateXLIFFForReportInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "xliffData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] xliffData,
        @WebParam(name = "layoutFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String layoutFileName,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param xliffData
     * @param locale
     * @param layoutFileName
     * @param password
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "updateXLIFFForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "updateXLIFFForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UpdateXLIFFForReport")
    @ResponseWrapper(localName = "updateXLIFFForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UpdateXLIFFForReportResponse")
    public boolean updateXLIFFForReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "xliffData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] xliffData,
        @WebParam(name = "layoutFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String layoutFileName,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param xliffData
     * @param bipSessionToken
     * @param locale
     * @param layoutFileName
     * @param reportAbsolutePath
     * @return
     *     returns boolean
     * @throws OperationFailedException_Exception
     * @throws InvalidParametersException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadXLIFFForReportInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "uploadXLIFFForReportInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UploadXLIFFForReportInSession")
    @ResponseWrapper(localName = "uploadXLIFFForReportInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UploadXLIFFForReportInSessionResponse")
    public boolean uploadXLIFFForReportInSession(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportAbsolutePath,
        @WebParam(name = "xliffData", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] xliffData,
        @WebParam(name = "layoutFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String layoutFileName,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String locale,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportRawDataChunk
     * @param userID
     * @param fileID
     * @param reportDataChunk
     * @param password
     * @return
     *     returns java.lang.String
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadReportDataChunkReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "uploadReportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UploadReportDataChunk")
    @ResponseWrapper(localName = "uploadReportDataChunkResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UploadReportDataChunkResponse")
    public String uploadReportDataChunk(
        @WebParam(name = "fileID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String fileID,
        @WebParam(name = "reportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] reportDataChunk,
        @WebParam(name = "reportRawDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportRawDataChunk,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param reportRawDataChunk
     * @param fileID
     * @param bipSessionToken
     * @param reportDataChunk
     * @return
     *     returns java.lang.String
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadReportDataChunkInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "uploadReportDataChunkInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UploadReportDataChunkInSession")
    @ResponseWrapper(localName = "uploadReportDataChunkInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.UploadReportDataChunkInSessionResponse")
    public String uploadReportDataChunkInSession(
        @WebParam(name = "fileID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String fileID,
        @WebParam(name = "reportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        byte[] reportDataChunk,
        @WebParam(name = "reportRawDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String reportRawDataChunk,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param userID
     * @param fileID
     * @param beginIdx
     * @param password
     * @param size
     * @return
     *     returns scm.bi12.ReportDataChunk
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "downloadReportDataChunkReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "downloadReportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.DownloadReportDataChunk")
    @ResponseWrapper(localName = "downloadReportDataChunkResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.DownloadReportDataChunkResponse")
    public ReportDataChunk downloadReportDataChunk(
        @WebParam(name = "fileID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String fileID,
        @WebParam(name = "beginIdx", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        int beginIdx,
        @WebParam(name = "size", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        int size,
        @WebParam(name = "userID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String userID,
        @WebParam(name = "password", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String password)
        throws AccessDeniedException_Exception, OperationFailedException_Exception
    ;

    /**
     * 
     * @param fileID
     * @param beginIdx
     * @param bipSessionToken
     * @param size
     * @return
     *     returns scm.bi12.ReportDataChunk
     * @throws OperationFailedException_Exception
     * @throws AccessDeniedException_Exception
     */
    @WebMethod
    @WebResult(name = "downloadReportDataChunkInSessionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
    @RequestWrapper(localName = "downloadReportDataChunkInSession", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.DownloadReportDataChunkInSession")
    @ResponseWrapper(localName = "downloadReportDataChunkInSessionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2", className = "scm.bi12.DownloadReportDataChunkInSessionResponse")
    public ReportDataChunk downloadReportDataChunkInSession(
        @WebParam(name = "fileID", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String fileID,
        @WebParam(name = "beginIdx", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        int beginIdx,
        @WebParam(name = "size", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        int size,
        @WebParam(name = "bipSessionToken", targetNamespace = "http://xmlns.oracle.com/oxp/service/v2")
        String bipSessionToken)
        throws AccessDeniedException_Exception, OperationFailedException_Exception
    ;

}
